In [156]:
import pandas as pd

In [157]:
def add_unique_location_column(df, lat_col='latitude', lon_col='longitude'):
    """
    Adds a new column to the DataFrame with unique location names (e.g., 'Location 1', 'Location 2')
    based on latitude and longitude values.

    Args:
        df (pd.DataFrame): The DataFrame containing latitude and longitude columns.
        lat_col (str): Name of the column for latitude. Default is 'latitude'.
        lon_col (str): Name of the column for longitude. Default is 'longitude'.

    Returns:
        pd.DataFrame: The DataFrame with a new column 'location'.
    """
    # Create a unique identifier for each latitude-longitude pair
    unique_coords = {}
    location_counter = 1

    def get_location(lat, lon):
        nonlocal location_counter
        coord = (lat, lon)
        if coord not in unique_coords:
            unique_coords[coord] = f"Location {location_counter}"
            location_counter += 1
        return unique_coords[coord]

    df['location'] = df.apply(lambda row: get_location(row[lat_col], row[lon_col]), axis=1)
    return df

In [158]:
# function to print the location corrdincates and timestamps
def print_location_info(df):
    for location, group in df.groupby('location'):
        print(f"{location}")
        group.sort_index(inplace=True)
        print(f"Lat, Lon: {group['SITE_LATITUDE'].iloc[0]}, {group['SITE_LONGITUDE'].iloc[0]}")
        print(f"First timestamp: {group.index[0]}")
        print(f"Last timestamp: {group.index[-1]}\n")

In [159]:
# Save the data to a file
def save_location_data(df, filepath):
    for location, group in df.groupby('location'):
        # add coordinates to file name
        
        group.to_csv(f"{filepath}/{location}_{group['SITE_LATITUDE'].iloc[0]}_{group['SITE_LONGITUDE'].iloc[0]}.csv")

# Egypt

In [160]:
df = pd.read_csv('Data/irradiation_measurements/CBE_Data/Egypt/CBE_Egypt.csv')
df['MEASURE_DATE'] = pd.to_datetime(df['MEASURE_DATE'])
df.set_index('MEASURE_DATE', inplace=True)
df.sort_index(inplace=True)
df.head()

              MEASURE_VALUE SITE_COUNTRY  SITE_LATITUDE  SITE_LONGITUDE
MEASURE_DATE
2023-09-01         6428.052        Egypt      29.887561       32.460447
2023-09-02         6601.826        Egypt      29.887561       32.460447
2023-09-03         6600.638        Egypt      29.887561       32.460447
2023-09-04         6391.094        Egypt      29.887561       32.460447
2023-09-05         6373.021        Egypt      29.887561       32.460447

In [161]:
df_loc = add_unique_location_column(df, lat_col='SITE_LATITUDE', lon_col='SITE_LONGITUDE')
df_loc.head()

,MEASURE_VALUE,SITE_COUNTRY,SITE_LATITUDE,SITE_LONGITUDE,location
MEASURE_DATE,,,,,
2023-09-01,6428.052,Egypt,29.887561,32.460447,Location 1
2023-09-02,6601.826,Egypt,29.887561,32.460447,Location 1
2023-09-03,6600.638,Egypt,29.887561,32.460447,Location 1
2023-09-04,6391.094,Egypt,29.887561,32.460447,Location 1
2023-09-05,6373.021,Egypt,29.887561,32.460447,Location 1

In [162]:
print_location_info(df_loc)

Location 1
Lat, Lon: 29.887561, 32.460447
First timestamp: 2023-09-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

In [163]:
save_location_data(df_loc, 'Data/irradiation_measurements/CBE_Data/Egypt/')

# Ghana

In [164]:
df = pd.read_csv('Data/irradiation_measurements/CBE_Data/Ghana/CBE_Ghana.csv')
df['MEASURE_DATE'] = pd.to_datetime(df['MEASURE_DATE'])
df.set_index('MEASURE_DATE', inplace=True)
df.sort_index(inplace=True)
df.head()

              MEASURE_VALUE SITE_COUNTRY  SITE_LATITUDE  SITE_LONGITUDE
MEASURE_DATE
2019-01-01              0.0        Ghana       5.645759       -0.105223
2019-01-02              0.0        Ghana       5.645759       -0.105223
2019-01-03              0.0        Ghana       5.645759       -0.105223
2019-01-04              0.0        Ghana       5.645759       -0.105223
2019-01-05              0.0        Ghana       5.645759       -0.105223

In [165]:
df_loc = add_unique_location_column(df, lat_col='SITE_LATITUDE', lon_col='SITE_LONGITUDE')
print_location_info(df_loc)

Location 1
Lat, Lon: 5.645759, -0.105223
First timestamp: 2019-01-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 2
Lat, Lon: 5.645686, 0.008678
First timestamp: 2020-01-31 00:00:00
Last timestamp: 2024-07-04 00:00:00

Location 3
Lat, Lon: -0.235111, 5.632167
First timestamp: 2021-02-25 00:00:00
Last timestamp: 2024-11-25 00:00:00

In [166]:
save_location_data(df_loc, 'Data/irradiation_measurements/CBE_Data/Ghana/')

# Kenya

In [167]:
df = pd.read_csv('Data/irradiation_measurements/CBE_Data/Kenya/CBE_Kenya.csv')
df['MEASURE_DATE'] = pd.to_datetime(df['MEASURE_DATE'])
df.set_index('MEASURE_DATE', inplace=True)
df.sort_index(inplace=True)
df.head()

              MEASURE_VALUE SITE_COUNTRY  SITE_LATITUDE  SITE_LONGITUDE
MEASURE_DATE
2017-04-01              0.0        Kenya           0.61           36.83
2017-04-02              0.0        Kenya           0.61           36.83
2017-04-03              0.0        Kenya           0.61           36.83
2017-04-04              0.0        Kenya           0.61           36.83
2017-04-05              0.0        Kenya           0.61           36.83

In [168]:
df_loc = add_unique_location_column(df, lat_col='SITE_LATITUDE', lon_col='SITE_LONGITUDE')
print_location_info(df_loc)

Location 1
Lat, Lon: 0.61, 36.83
First timestamp: 2017-04-01 00:00:00
Last timestamp: 2024-07-18 00:00:00

Location 10
Lat, Lon: -1.451111, 36.975687
First timestamp: 2023-09-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 11
Lat, Lon: -1.494448, 37.057094
First timestamp: 2023-09-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 12
Lat, Lon: -0.224, 35.88
First timestamp: 2023-09-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 13
Lat, Lon: -1.491302, 37.052862
First timestamp: 2023-10-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 14
Lat, Lon: -1.451315, 36.973008
First timestamp: 2023-10-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 2
Lat, Lon: 0.61, 36.8
First timestamp: 2019-05-02 00:00:00
Last timestamp: 2024-07-18 00:00:00

Location 3
Lat, Lon: -0.469974, 35.181874
First timestamp: 2019-05-28 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 4
Lat, Lon: -1.232761, 36.878509
First timestamp: 2019-07-24 00:00:00
Last timestamp: 2022-01-28 00:00:00

Location 5
Lat, Lon: -0.22, 35.86
First timestamp: 2020-12-22 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 6
Lat, Lon: -0.4, 35.92
First timestamp: 2021-01-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 7
Lat, Lon: -0.27, 35.85
First timestamp: 2021-01-01 00:00:00
Last timestamp: 2022-11-30 00:00:00

Location 8
Lat, Lon: -0.982, 37.0539
First timestamp: 2023-01-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 9
Lat, Lon: -0.227185, 35.884984
First timestamp: 2023-09-01 00:00:00
Last timestamp: 2024-11-25 00:00:00

In [169]:
save_location_data(df_loc, 'Data/irradiation_measurements/CBE_Data/Kenya/')

# Madagascar

In [170]:
df = pd.read_csv('Data/irradiation_measurements/CBE_Data/Madagascar/CBE_Madagascar.csv')
df['MEASURE_DATE'] = pd.to_datetime(df['MEASURE_DATE'])
df.set_index('MEASURE_DATE', inplace=True)
df.sort_index(inplace=True)
df.head()

              MEASURE_VALUE SITE_COUNTRY  SITE_LATITUDE  SITE_LONGITUDE
MEASURE_DATE
2023-02-13      1676.358833   Madagascar     -25.053564       46.947956
2023-02-14      7747.895667   Madagascar     -25.053564       46.947956
2023-02-15      7526.930500   Madagascar     -25.053564       46.947956
2023-02-16      7209.180750   Madagascar     -25.053564       46.947956
2023-02-17      6707.699583   Madagascar     -25.053564       46.947956

In [171]:
df_loc = add_unique_location_column(df, lat_col='SITE_LATITUDE', lon_col='SITE_LONGITUDE')
print_location_info(df_loc)

Location 1
Lat, Lon: -25.053564, 46.947956
First timestamp: 2023-02-13 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 2
Lat, Lon: -23.99, 45.12
First timestamp: 2023-09-28 00:00:00
Last timestamp: 2024-11-25 00:00:00

In [172]:
save_location_data(df_loc, 'Data/irradiation_measurements/CBE_Data/Madagascar/')

# Nigeria

In [173]:
df = pd.read_csv('Data/irradiation_measurements/CBE_Data/Nigeria/CBE_Nigeria.csv')
df['MEASURE_DATE'] = pd.to_datetime(df['MEASURE_DATE'])
df.set_index('MEASURE_DATE', inplace=True)
df.sort_index(inplace=True)
df.head()

              MEASURE_VALUE SITE_COUNTRY  SITE_LATITUDE  SITE_LONGITUDE
MEASURE_DATE
2020-02-19              0.0      Nigeria       9.076439        7.425385
2020-02-20              0.0      Nigeria       9.076439        7.425385
2020-02-21              0.0      Nigeria       9.076439        7.425385
2020-02-22              0.0      Nigeria       9.076439        7.425385
2020-02-23              0.0      Nigeria       9.076439        7.425385

In [174]:
df_loc = add_unique_location_column(df, lat_col='SITE_LATITUDE', lon_col='SITE_LONGITUDE')
print_location_info(df_loc)

Location 1
Lat, Lon: 9.076439, 7.425385
First timestamp: 2020-02-19 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 2
Lat, Lon: 6.448858, 7.392609
First timestamp: 2023-01-31 00:00:00
Last timestamp: 2024-11-25 00:00:00

Location 3
Lat, Lon: 7.38, 3.97
First timestamp: 2024-11-15 00:00:00
Last timestamp: 2024-11-23 00:00:00

In [175]:
save_location_data(df_loc, 'Data/irradiation_measurements/CBE_Data/Nigeria/')

# Somalia

In [176]:
df = pd.read_csv('Data/irradiation_measurements/CBE_Data/Somalia/CBE_Somalia.csv')
df['MEASURE_DATE'] = pd.to_datetime(df['MEASURE_DATE'])
df.set_index('MEASURE_DATE', inplace=True)
df.sort_index(inplace=True)
df.head()

              MEASURE_VALUE SITE_COUNTRY  SITE_LATITUDE  SITE_LONGITUDE
MEASURE_DATE
2024-01-27          221.470      Somalia       3.107191       43.637153
2024-01-28         5550.759      Somalia       3.107191       43.637153
2024-01-31         1624.788      Somalia       3.107191       43.637153
2024-02-01         5609.558      Somalia       3.107191       43.637153
2024-02-02         6353.845      Somalia       3.107191       43.637153

In [177]:
df_loc = add_unique_location_column(df, lat_col='SITE_LATITUDE', lon_col='SITE_LONGITUDE')
print_location_info(df_loc)

Location 1
Lat, Lon: 3.107191, 43.637153
First timestamp: 2024-01-27 00:00:00
Last timestamp: 2024-11-25 00:00:00

In [178]:
save_location_data(df_loc, 'Data/irradiation_measurements/CBE_Data/Somalia/')