In [8]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

# Ground Data EDA

In [2]:
measurement_folder = Path('Data/irradiation_measurements')
cbe_measurements = measurement_folder / 'CBE_Data'
mak_measurements = measurement_folder / 'MAK_physics_dept'
ministry_measurements = measurement_folder / 'ministry_energy_ug'

In [9]:
location = 'soroti'
soroti = pd.read_csv(ministry_measurements / f'{location}.csv')
soroti.head()

     datetime     ghi location
0  2020-02-01  2550.0   soroti
1  2020-02-02  6100.0   soroti
2  2020-02-03  4690.0   soroti
3  2020-02-04  6690.0   soroti
4  2020-02-05  6030.0   soroti

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(10, 5))

In [7]:
wadelai = pd.read_csv(ministry_measurements / 'wadelai.csv')
wadelai.head()

     datetime     ghi location
0  2020-02-01  4040.0  wadelai
1  2020-02-02  6300.0  wadelai
2  2020-02-03  3550.0  wadelai
3  2020-02-04  4980.0  wadelai
4  2020-02-05  3120.0  wadelai