In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from susse.estimators.validation.metrics import StatisticalMetrics

In [2]:
df_soroti = pd.read_csv('Data/irradiation_measurements/ministry_energy_ug/cleaned/Soroti/Soroti_2021.csv')
df_soroti['Day'] = pd.to_datetime(df_soroti['Day'])
df_soroti.set_index('Day', inplace=True)
df_soroti.head()

,Temperature (C),Temperature (SAT) (C),Rain (mm),GHI_1 (kWh/m2/day),GHI_2 (kWh/m2/day),GHI_SAT (kWh/m2/day),GHI (1) vs (2) (%),GHI (1) vs (SAT) (%),DHI (1) (kWh/m2/day),DHI (SAT) (kWh/m2/day),DHI (1) vs (SAT) (%)
Day,,,,,,,,,,,
2021-01-01,20.31,24.67,8.4,3.10,3.11,2.53,-0.35,18.50,2.25,1.60,28.86
2021-01-02,22.86,25.09,0.0,6.03,6.05,6.83,-0.29,-13.14,1.50,1.90,-26.98
2021-01-03,24.08,25.08,0.0,6.54,6.58,6.86,-0.66,-4.88,1.73,1.87,-7.77
2021-01-04,24.65,25.67,0.0,6.57,6.61,6.64,-0.65,-1.01,2.30,2.07,10.15
2021-01-05,24.87,25.31,0.0,6.51,6.54,6.83,-0.60,-4.97,1.77,1.84,-3.67

In [3]:
s_measured = df_soroti['GHI_1 (kWh/m2/day)'].to_numpy()
len(s_measured)

365

In [4]:
s_solacast = df_soroti['GHI_SAT (kWh/m2/day)'].to_numpy()
len(s_solacast)

365

In [ ]:
s_camsrad = pd.read_csv('Data/irradiation_estimates/CAMS_RAD_data/Soroti_CAMS-RAD2021.csv', skiprows=42, sep=';')
s_camsrad['# Observation period'] = pd.to_datetime
s_camsrad.head()

,# Observation period,TOA,Clear sky GHI,Clear sky BHI,Clear sky DHI,Clear sky BNI,GHI,BHI,DHI,BNI,Reliability
0,2021-01-01T00:00:00.0/2021-01-02T00:00:00.0,9703.3779,6924.5151,5348.9751,1575.5400,7844.1323,2899.7854,872.6318,2027.1537,976.3567,0.9861
1,2021-01-02T00:00:00.0/2021-01-03T00:00:00.0,9710.7305,7071.8867,5553.4219,1518.4650,8340.8477,6828.4688,5033.2959,1795.1730,7708.3745,0.9865
2,2021-01-03T00:00:00.0/2021-01-04T00:00:00.0,9718.6592,7214.1045,5875.7427,1338.3616,8709.7109,7071.1421,5546.0151,1525.1270,8250.0068,0.9861
3,2021-01-04T00:00:00.0/2021-01-05T00:00:00.0,9726.9834,7327.9458,6176.6104,1151.3353,9314.7461,6885.5967,4807.1934,2078.4031,7317.3408,0.9865
4,2021-01-05T00:00:00.0/2021-01-06T00:00:00.0,9735.8662,7304.4209,6028.0254,1276.3959,9145.0518,6962.7104,5194.1777,1768.5327,8091.7383,0.9861

  # Observation period;TOA;Clear sky GHI;Clear sky BHI;Clear sky DHI;Clear sky BNI;GHI;BHI;DHI;BNI;Reliability
0  2021-01-01T00:00:00.0/2021-01-02T00:00:00.0;97...
1  2021-01-02T00:00:00.0/2021-01-03T00:00:00.0;97...
2  2021-01-03T00:00:00.0/2021-01-04T00:00:00.0;97...
3  2021-01-04T00:00:00.0/2021-01-05T00:00:00.0;97...
4  2021-01-05T00:00:00.0/2021-01-06T00:00:00.0;97...